let gameJson = [
    {id:1, name:'Alien Isolation', img:'img/game1.png', price:64.99, link:'https://contate.me/AlienIsolation'},
    {id:2, name:'Batman Arkham City', img:'img/game2.png', price:49.99, link:'https://contate.me/Batmam'},
    {id:3, name:'Battlefield 4', img:'img/game3.png', price:69.99, link:'https://contate.me/Battlefield4'},
    {id:4, name:'Borderlands 3', img:'img/game4.png', price:54.99, link:'https://contate.me/Borderlands3'},
    {id:5, name:'Call of Duty', img:'img/game5.png', price:59.99, link:'https://contate.me/CallofDuty'},
    {id:6, name:'Cyber Punk 2077', img:'img/game6.png', price:69.99, link:'https://contate.me/CyberPunk2077'},
    {id:7, name:'Days Gone', img:'img/game7.png', price:69.99, link:'https://contate.me/DaysGone'},
    {id:8, name:'Destiny', img:'img/game8.png', price:54.99, link:'https://contate.me/Destiny'},
    {id:9, name:'Detroit', img:'img/game9.png', price:74.99, link:'https://contate.me/Detroit'},
    {id:10, name:'F1 2017', img:'img/game10.png', price:64.99, link:'https://contate.me/F12017'},
    {id:11, name:'Far Cry 4', img:'img/game11.png', price:59.99, link:'https://contate.me/FarCry4'},
    {id:12, name:'Final Fantasy XV', img:'img/game12.png', price:74.99, link:'https://contate.me/FinalFantasyXV'},
    {id:13, name:'God of War', img:'img/game13.png', price:74.99, link:'https://contate.me/GodofWar'},
    {id:14, name:'God of War 3', img:'img/game14.png', price:69.99, link:'https://contate.me/GodofWar3'},
    {id:15, name:'Horizon Chase', img:'img/game15.png', price:49.99, link:'https://contate.me/HorizonChase'},
    {id:16, name: 'Horizon Zero Down', img:'img/game16.png', price:79.99, link:'https://contate.me/HorizonZD'},
    {id:17, name:'Injustice', img:'img/game17.png', price:69.99, link:'https://contate.me/Injustice'},
    {id:18, name:'Mafia 3', img:'img/game18.png', price:59.99, link:'https://contate.me/Mafia3'},
    {id:19, name:'Mortal Kombat X', img:'img/game19.png', price:64.99, link:'https://contate.me/MortalKombatX'},
    {id:20, name:'Ratchet Clank', img:'img/game20.png', price:54.99, link:'https://contate.me/RatchetClank'},
    {id:21, name:'Second Son', img:'img/game21.png', price:69.99, link:'https://contate.me/SecondSon'},
    {id:22, name:'The Last of Us', img:'img/game22.png', price:69.99, link:'https://contate.me/TheLastofUs'},
    {id:23, name:'The Witcher 3', img:'img/game23.png', price:79.99, link:'https://contate.me/TheWitcher3'},
    {id:24, name:'Tom Clancys 1', img:'img/game24.png', price:59.99, link:'https://contate.me/TomClancys1'},
    {id:25, name:'Tom Clancys 2', img:'img/game25.png', price:64.99, link:'https://contate.me/TomClancys2'},
    {id:26, name:'UFC', img:'img/game26.png', price:64.99, link:'https://contate.me/UFC'},
    {id:27, name:'Uncharted 4', img:'img/game27.png', price:69.99, link:'https://contate.me/Uncharted4'},
    {id:28, name:'Uncharted Collection', img:'img/game28.png', price:54.99, link:'https://contate.me/UnchartedC'},
    {id:29, name:'Watch Dogs', img:'img/game29.png', price:54.99, link:'https://contate.me/WatchDogs'}
];